import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowUpRight, BookOpen, Check, CircleHelp, Copy, Link2, MessageSquareText, Plus, QrCode, Search, Send, Users, X } from 'lucide-react';
import QRCode from 'qrcode';
import './group-invites.css';
import './group-requests.css';

type ChatMessage = { id: string; username: string; mine: boolean; body: string; created_at: string };
type Dm = { conversation_id: string; peer_username: string; last_message: string | null; last_at: string | null };
type Group = { id: string; name: string; visibility: 'public' | 'private'; require_approval: number; role: 'admin' | 'member'; joined_at: string; last_message: string | null; last_at: string | null };
type RequestItem = { id: string; sender_id: string; sender_username: string; recipient_id: string; recipient_username: string; created_at: string; incoming: number };
type Invitation = { id: string; group_id: string; name: string; inviter_username: string };
type GroupJoinRequest = { id: string; group_id: string; name: string; username: string; created_at: string };
type MyGroupJoinRequest = { id: string; group_id: string; name: string; created_at: string };
type PublicGroup = { id: string; name: string; require_approval: number; member_count: number; is_member: number; request_pending: number };

function readGroupInviteToken() {
  const prefix = '#group-invite=';
  return location.hash.startsWith(prefix) ? location.hash.slice(prefix.length) : '';
}

function clearGroupInviteToken() {
  if (location.hash.startsWith('#group-invite=')) history.replaceState(null, '', `${location.pathname}${location.search}`);
}

function groupInviteUrl(token: string) {
  const origin = location.hostname === 'student-addit.pages.dev' || location.hostname.endsWith('.student-addit.pages.dev') ? 'https://student-addit.pages.dev' : location.origin;
  const invite = new URL('/', origin);
  invite.hash = `group-invite=${token}`;
  return invite.toString();
}

const appOrigin = location.hostname === 'student-addit.pages.dev' || location.hostname.endsWith('.student-addit.pages.dev') ? 'https://student-addit.mgp899123.workers.dev' : '';
const apiRoot = `${appOrigin}/api`;
const wsRoot = appOrigin ? appOrigin.replace(/^http/, 'ws') : `${location.protocol}//${location.host}`;

async function request<T>(path: string, token: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${apiRoot}${path}`, { ...init, headers: { 'content-type': 'application/json', authorization: `Bearer ${token}`, ...init.headers } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Could not complete that action.');
  return data as T;
}

export function CommunityChats({ token }: { token: string }) {
  const [dms, setDms] = useState<Dm[]>([]); const [groups, setGroups] = useState<Group[]>([]);
  const [requests, setRequests] = useState<RequestItem[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [joinRequests, setJoinRequests] = useState<GroupJoinRequest[]>([]); const [myJoinRequests, setMyJoinRequests] = useState<MyGroupJoinRequest[]>([]);
  const [selected, setSelected] = useState<{ kind: 'dm' | 'group'; id: string; label: string } | null>(null);
  const [friendId, setFriendId] = useState(''); const [groupName, setGroupName] = useState(''); const [visibility, setVisibility] = useState<'public' | 'private'>('public'); const [requireApproval, setRequireApproval] = useState(false);
  const [search, setSearch] = useState(''); const [chatSearch, setChatSearch] = useState(''); const [publicGroups, setPublicGroups] = useState<PublicGroup[]>([]); const [joiningPublicGroup, setJoiningPublicGroup] = useState(''); const [showTools, setShowTools] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [pendingInviteToken, setPendingInviteToken] = useState(readGroupInviteToken); const [invitePreview, setInvitePreview] = useState<{ id: string; name: string; visibility: string; require_approval: number; member_count: number; is_member: boolean; request_pending: boolean } | null>(null); const [invitePreviewError, setInvitePreviewError] = useState(''); const [joiningInvite, setJoiningInvite] = useState(false); const [previewRetry, setPreviewRetry] = useState(0);
  const refresh = useCallback(async () => {
    const [friendData, groupData, myRequests] = await Promise.all([request<{ conversations: Dm[]; requests: RequestItem[] }>('/friends', token), request<{ groups: Group[]; invitations: Invitation[]; joinRequests: GroupJoinRequest[] }>('/groups', token), request<{ requests: MyGroupJoinRequest[] }>('/group-join-requests', token)]);
    setDms(friendData.conversations); setRequests(friendData.requests); setGroups(groupData.groups); setInvitations(groupData.invitations); setJoinRequests(groupData.joinRequests); setMyJoinRequests(myRequests.requests);
  }, [token]);
  useEffect(() => { void refresh().catch((e) => setError(e.message)); }, [refresh]);
  useEffect(() => { const updateInvite = () => { const next = readGroupInviteToken(); if (next) { setPendingInviteToken(next); setInvitePreview(null); setInvitePreviewError(''); } }; window.addEventListener('hashchange', updateInvite); return () => window.removeEventListener('hashchange', updateInvite); }, []);
  useEffect(() => {
    const query = search.trim();
    if (query.length < 2) { setPublicGroups([]); return; }
    let cancelled = false;
    const timer = setTimeout(() => { void request<{ groups: PublicGroup[] }>(`/groups/discover?q=${encodeURIComponent(query)}`, token).then((data) => { if (!cancelled) setPublicGroups(data.groups); }).catch((e) => { if (!cancelled) setError(e.message); }); }, 250);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [search, token]);
  useEffect(() => {
    if (!pendingInviteToken) return;
    setInvitePreview(null); setInvitePreviewError('');
    void request<{ group: NonNullable<typeof invitePreview> }>('/group-invites/preview', token, { method: 'POST', body: JSON.stringify({ token: pendingInviteToken }) })
      .then((data) => setInvitePreview(data.group)).catch((e) => setInvitePreviewError(e.message || 'This invite link is no longer available.'));
  }, [pendingInviteToken, previewRetry, token]);
  const submit = async (event: FormEvent, action: () => Promise<void>) => { event.preventDefault(); setError(''); setNotice(''); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not complete that action.'); } };
  const sendRequest = async (event: FormEvent) => submit(event, async () => { await request('/friend-requests', token, { method: 'POST', body: JSON.stringify({ username: friendId }) }); setFriendId(''); setNotice('Request sent.'); await refresh(); });
  const createGroup = async (event: FormEvent) => submit(event, async () => { const data = await request<{ group: Group }>('/groups', token, { method: 'POST', body: JSON.stringify({ name: groupName, visibility, requireApproval }) }); setGroupName(''); setShowTools(false); setNotice(`“${data.group.name}” is ready. Share an invite link from its group settings.`); await refresh(); setSelected({ kind: 'group', id: data.group.id, label: data.group.name }); });
  const joinPublicGroup = async (group: PublicGroup) => { setJoiningPublicGroup(group.id); setError(''); setNotice(''); try { const data = await request<{ status: string; group: { id: string; name: string } }>(`/groups/${encodeURIComponent(group.id)}/join`, token, { method: 'POST' }); setPublicGroups((current) => current.map((item) => item.id === group.id ? { ...item, is_member: data.status === 'joined' || data.status === 'member' ? 1 : item.is_member, request_pending: data.status === 'pending' ? 1 : item.request_pending } : item)); await refresh(); if (data.status === 'joined' || data.status === 'member') { setSelected({ kind: 'group', id: data.group.id, label: data.group.name }); setNotice(`You joined ${data.group.name}.`); } else setNotice(`Your request to join ${data.group.name} is waiting for an admin.`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not join this group.'); } finally { setJoiningPublicGroup(''); } };
  const joinFromInvite = async () => { if (!pendingInviteToken) return; setJoiningInvite(true); setError(''); try { const data = await request<{ status: string; group: { id: string; name: string } }>('/group-invites/join', token, { method: 'POST', body: JSON.stringify({ token: pendingInviteToken }) }); clearGroupInviteToken(); setPendingInviteToken(''); setInvitePreview(null); await refresh(); if (data.status === 'joined' || data.status === 'member') { setSelected({ kind: 'group', id: data.group.id, label: data.group.name }); setNotice(data.status === 'member' ? `You’re already in ${data.group.name}.` : `You joined ${data.group.name}.`); } else setNotice(`Your request to join ${data.group.name} is waiting for an admin.`); } catch (e) { setInvitePreviewError(e instanceof Error ? e.message : 'This invite link is no longer available.'); } finally { setJoiningInvite(false); } };
  const respond = async (type: 'friend-requests' | 'group-invitations', item: { id: string }, action: 'accept' | 'decline') => {
    setError(''); try { await request(`/${type}/${encodeURIComponent(item.id)}/respond`, token, { method: 'POST', body: JSON.stringify({ action }) }); await refresh(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not respond.'); }
  };
  const respondJoinRequest = async (item: GroupJoinRequest, action: 'accept' | 'decline') => { setError(''); try { await request(`/group-join-requests/${encodeURIComponent(item.id)}/respond`, token, { method: 'POST', body: JSON.stringify({ action }) }); await refresh(); if (action === 'accept') setSelected({ kind: 'group', id: item.group_id, label: item.name }); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update the join request.'); } };
  const cancelMyJoinRequest = async (item: MyGroupJoinRequest) => { setError(''); try { await request(`/group-join-requests/${encodeURIComponent(item.id)}`, token, { method: 'DELETE' }); setMyJoinRequests((current) => current.filter((requestItem) => requestItem.id !== item.id)); setPublicGroups((current) => current.map((group) => group.id === item.group_id ? { ...group, request_pending: 0 } : group)); setNotice(`Your request for ${item.name} was withdrawn.`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not cancel the request.'); } };
  const inbox = [
    ...groups.map((group) => ({ kind: 'group' as const, id: group.id, label: group.name, preview: group.last_message || (group.role === 'admin' ? 'Group · you’re an admin' : 'Group conversation'), sortAt: group.last_at || group.joined_at, icon: 'group' as const })),
    ...dms.map((dm) => ({ kind: 'dm' as const, id: dm.conversation_id, label: `#${dm.peer_username}`, preview: dm.last_message || 'Private conversation', sortAt: dm.last_at || '', icon: dm.peer_username[0]?.toUpperCase() || '#' })),
  ].filter((item) => `${item.label} ${item.preview}`.toLowerCase().includes(chatSearch.trim().toLowerCase())).sort((a, b) => b.sortAt.localeCompare(a.sortAt));
  return <div className={`page-wrap community-chat-page ${selected ? 'has-selected-chat' : ''}`}>
    <div className="community-grid">
    <section className="community-inbox">
      <header className="community-inbox-header"><div><span className="eyebrow">YOUR PEOPLE, YOUR ROOMS</span><h1>Chats</h1></div><button className="community-new-chat" onClick={() => setShowTools((value) => !value)} aria-label={showTools ? 'Close new chat options' : 'Start a new chat'} title="Start a new chat"><Plus size={21}/></button></header>
      <label className="community-inbox-search"><Search size={17}/><input value={chatSearch} onChange={(event) => setChatSearch(event.target.value)} placeholder="Search or start a new chat" aria-label="Search chats"/><button type="button" onClick={() => setChatSearch('')} aria-label="Clear search" hidden={!chatSearch}><X size={15}/></button></label>
      {showTools && <section className="community-new-chat-tools">
        <form className="community-inline-form" onSubmit={(event) => void sendRequest(event)}><div><span className="eyebrow">PRIVATE CHAT</span><strong>Find someone by adda ID</strong></div><div className="community-form-row"><input value={friendId} onChange={(event) => setFriendId(event.target.value)} placeholder="Their adda ID" aria-label="Adda ID"/><button disabled={!friendId.trim()}><Users size={16}/> Send request</button></div></form>
        <form className="community-inline-form" onSubmit={(event) => void createGroup(event)}><div><span className="eyebrow">A ROOM OF YOUR OWN</span><strong>Create a group</strong></div><input required minLength={2} maxLength={80} value={groupName} onChange={(event) => setGroupName(event.target.value)} placeholder="Group name"/><div className="community-form-row"><select value={visibility} onChange={(event) => { const next = event.target.value as 'public' | 'private'; setVisibility(next); setRequireApproval(next === 'private'); }}><option value="public">Public · anyone can find it</option><option value="private">Private · invite link only</option></select><button><Plus size={16}/> Create</button></div>{visibility === 'public' && <label className="community-approval-toggle"><input type="checkbox" checked={requireApproval} onChange={(event) => setRequireApproval(event.target.checked)}/><span>Approve new members before they join</span></label>}</form>
        <form className="community-discover-form" onSubmit={(event) => event.preventDefault()}><div><span className="eyebrow">PUBLIC GROUPS</span><strong>Find a room by name</strong></div><label className="community-search-box"><Search size={16}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search public groups" aria-label="Search public groups"/></label>{search.trim().length >= 2 && <div className="community-discover-results">{publicGroups.map((group) => <div className="community-discover-card" key={group.id}><span className="community-avatar"><Users size={16}/></span><div><b>{group.name}</b><small>{group.member_count} {group.member_count === 1 ? 'member' : 'members'} · {group.require_approval ? 'admin approval' : 'open to join'}</small></div><button type="button" disabled={!!group.is_member || !!group.request_pending || joiningPublicGroup === group.id} onClick={() => void joinPublicGroup(group)}>{group.is_member ? 'Joined' : group.request_pending ? 'Request sent' : joiningPublicGroup === group.id ? 'Joining…' : group.require_approval ? 'Request' : 'Join'}</button></div>)}{!publicGroups.length && <p className="community-muted">No public groups match that search yet.</p>}</div>}</form>
      </section>}
      {(error || notice) && <div className={`study-status ${error ? 'error' : ''}`}>{error || notice}</div>}
      <div className="community-inbox-list" aria-label="Conversations">
        {inbox.map((item) => <button className={`community-inbox-row ${selected?.id === item.id ? 'selected' : ''}`} key={`${item.kind}:${item.id}`} onClick={() => setSelected({ kind: item.kind, id: item.id, label: item.label })}><span className={`community-inbox-avatar ${item.icon === 'group' ? 'group' : ''}`}>{item.icon === 'group' ? <Users size={18}/> : item.icon}</span><span className="community-inbox-copy"><span><b>{item.label}</b><time>{formatInboxTime(item.sortAt)}</time></span><small>{item.preview}</small></span></button>)}
        {!inbox.length && <div className="community-inbox-empty"><MessageSquareText size={23}/><strong>{chatSearch ? 'No chats found' : 'Your chats will appear here'}</strong><span>{chatSearch ? 'Try another adda ID or group name.' : 'Start a private chat or create a group with the + button.'}</span></div>}
      </div>
      {!!(requests.length || invitations.length || joinRequests.length || myJoinRequests.length) && <details className="community-inbox-requests"><summary>Requests and invitations <span>{requests.length + invitations.length + joinRequests.length + myJoinRequests.length}</span></summary>
        {!!requests.length && <div className="community-list-block"><h3>Friend requests</h3>{requests.map((item) => <div className="community-person" key={item.id}><span className="community-avatar">{(item.incoming ? item.sender_username : item.recipient_username)[0]?.toUpperCase()}</span><div><b>#{item.incoming ? item.sender_username : item.recipient_username}</b><small>{item.incoming ? 'Wants to chat' : 'Waiting for their reply'}</small></div>{!!item.incoming && <div className="community-actions"><button onClick={() => void respond('friend-requests', item, 'accept')} title="Accept"><Check size={16}/></button><button onClick={() => void respond('friend-requests', item, 'decline')} title="Decline"><X size={16}/></button></div>}</div>)}</div>}
        {!!invitations.length && <div className="community-list-block"><h3>Group invitations</h3>{invitations.map((item) => <div className="community-person" key={item.id}><span className="community-avatar"><Users size={16}/></span><div><b>{item.name}</b><small>From #{item.inviter_username}</small></div><div className="community-actions"><button onClick={() => void respond('group-invitations', item, 'accept')} title="Accept"><Check size={16}/></button><button onClick={() => void respond('group-invitations', item, 'decline')} title="Decline"><X size={16}/></button></div></div>)}</div>}
        {!!joinRequests.length && <div className="community-list-block"><h3>Group join requests <span>{joinRequests.length}</span></h3>{joinRequests.map((item) => <div className="community-person" key={item.id}><span className="community-avatar">{item.username[0]?.toUpperCase()}</span><div><b>#{item.username}</b><small>Wants to join {item.name}</small></div><div className="community-actions"><button onClick={() => void respondJoinRequest(item, 'accept')} title="Approve"><Check size={16}/></button><button onClick={() => void respondJoinRequest(item, 'decline')} title="Decline"><X size={16}/></button></div></div>)}</div>}
        {!!myJoinRequests.length && <div className="community-list-block"><h3>Your join requests <span>{myJoinRequests.length}</span></h3>{myJoinRequests.map((item) => <div className="community-person" key={item.id}><span className="community-avatar"><Users size={15}/></span><div><b>{item.name}</b><small>Waiting for a group admin</small></div><button className="community-cancel-request" onClick={() => void cancelMyJoinRequest(item)}>Cancel</button></div>)}</div>}
      </details>}
    </section>
    <section className="community-room">{selected ? <CommunityRoom key={`${selected.kind}:${selected.id}`} token={token} kind={selected.kind} id={selected.id} label={selected.label} isAdmin={groups.some((group) => group.id === selected.id && group.role === 'admin')} onRefresh={refresh} onBack={() => setSelected(null)}/> : <div className="community-room-empty"><div><MessageSquareText size={25}/></div><h2>Your next good conversation.</h2><p>Choose a chat from the list, or start a new one.</p></div>}</section></div>
    {!!pendingInviteToken && <div className="community-invite-backdrop"><section className="community-invite-dialog" role="dialog" aria-modal="true" aria-labelledby="group-invite-title"><button className="community-invite-close" onClick={() => { clearGroupInviteToken(); setPendingInviteToken(''); }} aria-label="Close invite"><X size={18}/></button><div className="community-avatar"><Link2 size={18}/></div><span className="eyebrow">YOU’VE BEEN INVITED</span>{invitePreview ? <><h2 id="group-invite-title">Join {invitePreview.name}?</h2><p>{invitePreview.member_count} {invitePreview.member_count === 1 ? 'member' : 'members'} · {invitePreview.visibility === 'private' ? 'Private group' : 'Public group'}{invitePreview.require_approval ? ' · admin approval required' : ''}</p>{invitePreview.is_member ? <button className="small-action" onClick={() => { clearGroupInviteToken(); setPendingInviteToken(''); setSelected({ kind: 'group', id: invitePreview.id, label: invitePreview.name }); }}>Open group <ArrowUpRight size={15}/></button> : invitePreview.request_pending ? <button className="small-action" disabled>Request sent · waiting for an admin</button> : <button className="small-action" onClick={() => void joinFromInvite()} disabled={joiningInvite}>{joiningInvite ? 'Joining…' : invitePreview.require_approval ? 'Request to join' : 'Join group'} <ArrowUpRight size={15}/></button>}</> : <><h2 id="group-invite-title">{invitePreviewError ? 'Invite unavailable' : 'Checking your invite…'}</h2><p>{invitePreviewError || 'One moment while we look up the group.'}</p><div className="community-invite-dialog-actions"><button onClick={() => { clearGroupInviteToken(); setPendingInviteToken(''); }}>{invitePreviewError ? 'Close' : 'Not now'}</button>{invitePreviewError && <button onClick={() => { setInvitePreviewError(''); setPreviewRetry((retry) => retry + 1); }}>Try again</button>}</div></>}</section></div>}
  </div>;
}

function formatInboxTime(value: string) {
  if (!value) return '';
  const date = new Date(value.replace(' ', 'T') + (value.includes('Z') ? '' : 'Z'));
  return Number.isNaN(date.getTime()) ? '' : date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
}

function CommunityRoom({ token, kind, id, label, isAdmin, onRefresh, onBack }: { token: string; kind: 'dm' | 'group'; id: string; label: string; isAdmin: boolean; onRefresh: () => Promise<void>; onBack: () => void }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [hasOlder, setHasOlder] = useState(false); const [value, setValue] = useState(''); const [error, setError] = useState(''); const [live, setLive] = useState(false); const [section, setSection] = useState<'chat' | 'studies' | 'polls'>('chat'); const socketRef = useRef<WebSocket | null>(null); const listRef = useRef<HTMLDivElement>(null); const preserveScrollRef = useRef<{ height: number; top: number } | null>(null);
  const messagePath = kind === 'dm' ? `/conversations/${encodeURIComponent(id)}/messages` : `/groups/${encodeURIComponent(id)}/messages`;
  const load = useCallback(async () => { const data = await request<{ messages: ChatMessage[] }>(messagePath, token); setMessages(data.messages); setHasOlder(data.messages.length === 200); }, [messagePath, token]);
  const loadOlder = async () => { const first = messages[0]; if (!first) return; try { const data = await request<{ messages: ChatMessage[] }>(`${messagePath}?before=${encodeURIComponent(`${first.created_at}|${first.id}`)}`, token); if (listRef.current) preserveScrollRef.current = { height: listRef.current.scrollHeight, top: listRef.current.scrollTop }; setMessages((current) => [...data.messages, ...current]); setHasOlder(data.messages.length === 200); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load older messages.'); } };
  useEffect(() => { void load().catch((e) => setError(e.message)); let stopped = false; let timer: ReturnType<typeof setTimeout> | undefined; let delay = 1000;
    const connect = () => { if (stopped) return; const ws = new WebSocket(`${wsRoot}/api/ws/room?kind=${kind}&id=${encodeURIComponent(id)}&token=${encodeURIComponent(token)}`); socketRef.current = ws;
      ws.onopen = () => { if (!stopped) { setLive(true); delay = 1000; void load(); } }; ws.onmessage = (event) => { try { const data = JSON.parse(String(event.data)); if (data.type === 'message' && data.message?.id) setMessages((current) => current.some((m) => m.id === data.message.id) ? current : [...current, data.message as ChatMessage]); } catch { /* ignore invalid frames */ } };
      ws.onclose = () => { if (!stopped) { setLive(false); timer = setTimeout(connect, delay); delay = Math.min(delay * 2, 8000); } }; ws.onerror = () => ws.close(); };
    connect(); return () => { stopped = true; if (timer) clearTimeout(timer); socketRef.current?.close(); socketRef.current = null; };
  }, [id, kind, load, token]);
  useEffect(() => { const list = listRef.current; if (!list) return; const preserve = preserveScrollRef.current; if (preserve) { list.scrollTop = preserve.top + list.scrollHeight - preserve.height; preserveScrollRef.current = null; } else list.scrollTop = list.scrollHeight; }, [messages]);
  const send = (event: FormEvent) => { event.preventDefault(); const body = value.trim(); if (!body || socketRef.current?.readyState !== WebSocket.OPEN) return; socketRef.current.send(JSON.stringify({ body })); setValue(''); };
  return <><header className="community-room-head"><button className="community-back-button" onClick={onBack} aria-label="Back to chats"><ArrowLeft size={19}/></button><div className="community-avatar"><MessageSquareText size={18}/></div><div><b>{label}</b><small>{kind === 'dm' ? 'PRIVATE CHAT · ONLY YOU TWO' : `GROUP ROOM · ${isAdmin ? 'YOU ARE ADMIN' : 'MEMBER'}`}</small></div><span className={`live-status ${live ? '' : 'offline'}`}><i className={live ? 'online-dot' : 'offline-dot'}/>{live ? 'LIVE' : 'RECONNECTING'}</span></header>
    {kind === 'group' && <div className="community-room-tabs"><button className={section === 'chat' ? 'active' : ''} onClick={() => setSection('chat')}><MessageSquareText size={15}/> Chat</button><button className={section === 'studies' ? 'active' : ''} onClick={() => setSection('studies')}><BookOpen size={15}/> Studies</button><button className={section === 'polls' ? 'active' : ''} onClick={() => setSection('polls')}><CircleHelp size={15}/> Polls</button></div>}
    {section === 'chat' ? <>{hasOlder && <button className="community-load-older" onClick={() => void loadOlder()}>Load earlier messages</button>}<div className="community-message-list" ref={listRef}>{messages.length ? messages.map((m) => <article className={`community-message ${m.mine ? 'mine' : ''}`} key={m.id}><div className="community-message-meta"><b>#{m.username}</b><time>{new Date(m.created_at.replace(' ', 'T') + (m.created_at.includes('Z') ? '' : 'Z')).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div><p>{m.body}</p></article>) : <div className="community-room-empty small"><MessageSquareText size={22}/><p>Send the first message.</p></div>}</div><form className="composer" onSubmit={send}><input disabled={!live} value={value} onChange={(e) => setValue(e.target.value)} maxLength={2000} placeholder={live ? 'Say something nice...' : 'Reconnecting to this room…'} aria-label="Message"/><button disabled={!live || !value.trim()}><Send size={18}/></button></form>{error && <div className="chat-error">{error}</div>}</> : kind === 'group' && section === 'studies' ? <GroupStudies token={token} id={id} isAdmin={isAdmin}/> : kind === 'group' ? <GroupPolls token={token} id={id} isAdmin={isAdmin}/> : null}
    {kind === 'group' && <GroupManage token={token} id={id} isAdmin={isAdmin} onRefresh={onRefresh}/>}
  </>;
}

function GroupManage({ token, id, isAdmin, onRefresh }: { token: string; id: string; isAdmin: boolean; onRefresh: () => Promise<void> }) {
  const [username, setUsername] = useState(''); const [members, setMembers] = useState<{ user_id: string; username: string; role: string }[]>([]); const [groupName, setGroupName] = useState(''); const [visibility, setVisibility] = useState<'public' | 'private'>('public'); const [requireApproval, setRequireApproval] = useState(false); const [inviteLinks, setInviteLinks] = useState<{ id: string; created_at: string; use_count: number; last_used_at: string | null }[]>([]); const [inviteUrl, setInviteUrl] = useState(''); const [inviteQr, setInviteQr] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [copied, setCopied] = useState(false);
  const load = useCallback(async () => { const data = await request<{ members: typeof members; group: { name: string; visibility: 'public' | 'private'; require_approval: number }; inviteLinks: typeof inviteLinks }>(`/groups/${encodeURIComponent(id)}`, token); setMembers(data.members); setGroupName(data.group.name); setVisibility(data.group.visibility); setRequireApproval(!!data.group.require_approval); setInviteLinks(data.inviteLinks ?? []); }, [id, token]); useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  if (!isAdmin) return null;
  const invite = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}/invitations`, token, { method: 'POST', body: JSON.stringify({ username }) }); setUsername(''); setError('Invitation sent.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not invite member.'); } };
  const save = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}`, token, { method: 'PATCH', body: JSON.stringify({ name: groupName, visibility, requireApproval }) }); setError('Group settings saved.'); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save settings.'); } };
  const remove = async (userId: string) => { try { await request(`/groups/${encodeURIComponent(id)}/members?userId=${encodeURIComponent(userId)}`, token, { method: 'DELETE' }); await load(); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove member.'); } };
  const createInviteLink = async () => { setBusy(true); setError(''); try { const data = await request<{ inviteLink: { id: string; token: string } }>(`/groups/${encodeURIComponent(id)}/invite-links`, token, { method: 'POST' }); const url = groupInviteUrl(data.inviteLink.token); setInviteUrl(url); setInviteQr(await QRCode.toDataURL(url, { errorCorrectionLevel: 'M', margin: 2, width: 240, color: { dark: '#28302a', light: '#fbfaf6' } })); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create an invite link.'); } finally { setBusy(false); } };
  const copyInvite = async () => { try { await navigator.clipboard.writeText(inviteUrl); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { const field = document.createElement('textarea'); field.value = inviteUrl; field.style.position = 'fixed'; field.style.opacity = '0'; document.body.appendChild(field); field.select(); const ok = document.execCommand('copy'); field.remove(); if (ok) { setCopied(true); setTimeout(() => setCopied(false), 1800); } else setError('Copy was blocked. Select and copy the invite link instead.'); } };
  const shareInvite = async () => { if (navigator.share) { try { await navigator.share({ title: `${groupName} · Adda group`, text: `Join ${groupName} on Adda`, url: inviteUrl }); } catch (e) { if (!(e instanceof DOMException && e.name === 'AbortError')) setError('Could not open the share sheet.'); } } else await copyInvite(); };
  const revokeInvite = async (linkId: string) => { if (!window.confirm('Revoke this group invite link? Anyone holding it will no longer be able to join.')) return; try { await request(`/groups/${encodeURIComponent(id)}/invite-links/${encodeURIComponent(linkId)}`, token, { method: 'DELETE' }); setInviteUrl(''); setInviteQr(''); await load(); setError('Invite link revoked.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not revoke this link.'); } };
  const downloadQr = () => { if (!inviteQr) return; const link = document.createElement('a'); link.href = inviteQr; link.download = `${groupName.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'adda'}-group-invite.png`; link.click(); };
  return <details className="community-admin-tools"><summary>Group admin · manage room</summary><form className="community-resource-compose" onSubmit={(e) => void save(e)}><input value={groupName} onChange={(e) => setGroupName(e.target.value)} placeholder="Group name"/><div className="community-form-row"><select value={visibility} onChange={(e) => setVisibility(e.target.value as 'public' | 'private')}><option value="public">Public · searchable</option><option value="private">Private · invite only</option></select><button><Check size={15}/> Save</button></div><label className="community-approval-toggle"><input type="checkbox" checked={requireApproval} onChange={(e) => setRequireApproval(e.target.checked)}/><span>Approve new members before they join</span></label></form>
    <section className="community-invite-tools"><div className="community-invite-tools-head"><div><b><Link2 size={15}/> Invite people</b><small>Links work for anyone you share them with. Revoke one any time.</small></div><button type="button" onClick={() => { if (!inviteLinks.length || window.confirm('Create a new link and revoke the existing one?')) void createInviteLink(); }} disabled={busy}><Link2 size={15}/>{busy ? 'Creating…' : inviteLinks.length ? 'Rotate link' : 'Create invite link'}</button></div>
      {!!inviteLinks.length && !inviteUrl && <p className="community-muted">There’s an active link ({inviteLinks[0].use_count} joins). For privacy, Adda only shows a new link once. Rotate it to get a fresh copy and QR code.</p>}
      {!!inviteUrl && <div className="community-share-link"><label><span>Shareable invite link</span><input readOnly value={inviteUrl} onFocus={(event) => event.currentTarget.select()}/></label><div className="community-share-actions"><button type="button" onClick={() => void copyInvite()}><Copy size={14}/>{copied ? 'Copied' : 'Copy link'}</button><button type="button" onClick={() => void shareInvite()}><ArrowUpRight size={14}/>Share</button><button type="button" onClick={downloadQr} disabled={!inviteQr}><QrCode size={14}/>Save QR</button></div>{inviteQr && <div className="community-invite-qr"><img src={inviteQr} alt={`QR code to join ${groupName}`}/><span>Scan to preview and join this group</span></div>}</div>}
      {inviteLinks.map((link) => <div className="community-active-link" key={link.id}><span><Link2 size={14}/> Active invite · {link.use_count} {link.use_count === 1 ? 'join' : 'joins'}</span><button type="button" onClick={() => void revokeInvite(link.id)}>Revoke</button></div>)}
    </section><form className="community-form-row" onSubmit={(e) => void invite(e)}><input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Invite by adda ID" aria-label="Invite by adda ID"/><button disabled={!username.trim()}><Plus size={15}/> Invite</button></form>{members.map((m) => <div className="community-member-row" key={m.user_id}><span>#{m.username}</span><small>{m.role}</small>{m.role !== 'admin' && <button onClick={() => void remove(m.user_id)}>Remove</button>}</div>)}{error && <p className="community-muted">{error}</p>}</details>;
}

function GroupStudies({ token, id, isAdmin }: { token: string; id: string; isAdmin: boolean }) {
  const [sections, setSections] = useState<{ id: string; name: string; post_count: number }[]>([]); const [selected, setSelected] = useState(''); const [posts, setPosts] = useState<{ id: string; body: string; author_username: string; created_at: string; attachments?: { id: string; fileName: string; contentType: string; sizeBytes: number }[] }[]>([]); const [name, setName] = useState(''); const [body, setBody] = useState(''); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState('');
  const loadSections = useCallback(async () => { const data = await request<{ sections: typeof sections }>(`/groups/${encodeURIComponent(id)}/studies`, token); setSections(data.sections); if (!selected && data.sections[0]) setSelected(data.sections[0].id); }, [id, selected, token]);
  const loadPosts = useCallback(async () => { if (!selected) return setPosts([]); const data = await request<{ posts: typeof posts }>(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(selected)}`, token); setPosts(data.posts); }, [id, selected, token]);
  useEffect(() => { void loadSections().catch((e) => setError(e.message)); }, [loadSections]); useEffect(() => { void loadPosts().catch((e) => setError(e.message)); }, [loadPosts]);
  useEffect(() => { if (!selected) return; let stopped = false; let timer: ReturnType<typeof setTimeout> | undefined; let socket: WebSocket | null = null; const connect = async () => { try { const { ticket } = await request<{ ticket: string }>('/studies/ws-ticket', token, { method: 'POST', body: JSON.stringify({ sectionId: selected }) }); if (stopped) return; const ws = new WebSocket(`${wsRoot}/api/ws/studies?sectionId=${encodeURIComponent(selected)}&ticket=${encodeURIComponent(ticket)}`); socket = ws; ws.onmessage = (event) => { try { if (JSON.parse(String(event.data)).type !== 'connected') { void loadPosts(); void loadSections(); } } catch { void loadPosts(); } }; ws.onclose = () => { if (!stopped) timer = setTimeout(() => void connect(), 2500); }; ws.onerror = () => ws?.close(); } catch { if (!stopped) timer = setTimeout(() => void connect(), 4500); } }; void connect(); return () => { stopped = true; if (timer) clearTimeout(timer); socket?.close(); }; }, [selected, token, loadPosts, loadSections]);
  const createSection = async (e: FormEvent) => { e.preventDefault(); try { const data = await request<{ section: { id: string } }>(`/groups/${encodeURIComponent(id)}/studies/sections`, token, { method: 'POST', body: JSON.stringify({ name }) }); setName(''); setSelected(data.section.id); await loadSections(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create folder.'); } };
  const post = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(selected)}`, token, { method: 'POST', body: JSON.stringify({ body }) }); setBody(''); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not post.'); } };
  const upload = async (e: FormEvent) => { e.preventDefault(); if (!file || !selected) return; try { const response = await fetch(`${apiRoot}/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(selected)}/files`, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': file.type || 'application/octet-stream', 'x-file-name': encodeURIComponent(file.name) }, body: file }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Could not upload this file.'); setFile(null); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not upload this file.'); } };
  const archive = async (sectionId: string) => { try { await request(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(sectionId)}`, token, { method: 'PATCH', body: JSON.stringify({ archived: true }) }); if (selected === sectionId) setSelected(''); await loadSections(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not archive folder.'); } };
  const renameSection = async (sectionId: string, current: string) => { const next = window.prompt('Rename this Study folder', current); if (next === null || !next.trim()) return; try { await request(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(sectionId)}`, token, { method: 'PATCH', body: JSON.stringify({ name: next }) }); await loadSections(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not rename folder.'); } };
  const editPost = async (postId: string, current: string) => { const next = window.prompt('Edit this study note', current); if (next === null || !next.trim()) return; try { await request(`/groups/${encodeURIComponent(id)}/studies/posts/${encodeURIComponent(postId)}`, token, { method: 'PATCH', body: JSON.stringify({ body: next }) }); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update note.'); } };
  const deletePost = async (postId: string) => { if (!window.confirm('Remove this study post and its attachment?')) return; try { await request(`/groups/${encodeURIComponent(id)}/studies/posts/${encodeURIComponent(postId)}`, token, { method: 'DELETE' }); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove post.'); } };
  return <div className="community-resource"><div className="community-resource-heading"><BookOpen size={20}/><div><b>Group Studies</b><small>Shared with members of this group</small></div></div>{isAdmin && <form className="community-form-row" onSubmit={(e) => void createSection(e)}><input value={name} onChange={(e) => setName(e.target.value)} placeholder="New study folder"/><button><Plus size={15}/> Folder</button></form>}<div className="community-study-sections">{sections.map((s) => <span className={selected === s.id ? 'active' : ''} key={s.id}><button onClick={() => setSelected(s.id)}>{s.name}</button>{isAdmin && <><button title="Rename folder" onClick={() => void renameSection(s.id, s.name)}>✎</button><button title="Archive folder" onClick={() => void archive(s.id)}><X size={12}/></button></>}</span>)}</div>{selected && isAdmin && <><form className="community-resource-compose" onSubmit={(e) => void post(e)}><textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder="Share a study note..."/><button disabled={!body.trim()}><Send size={15}/> Post</button></form><form className="community-form-row community-file-upload" onSubmit={(e) => void upload(e)}><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.gif,.txt,.doc,.docx,.ppt,.pptx,.xls,.xlsx" onChange={(e) => setFile(e.target.files?.[0] ?? null)}/><button disabled={!file}><BookOpen size={15}/> Upload file</button></form></>}{posts.map((p) => <article className="community-resource-post" key={p.id}><div className="community-study-post-head"><small>#{p.author_username}</small>{isAdmin && <span><button onClick={() => void editPost(p.id, p.body)} title="Edit note">Edit</button><button onClick={() => void deletePost(p.id)} title="Remove post">Remove</button></span>}</div>{p.body && <p>{p.body}</p>}{p.attachments?.map((a) => <a key={a.id} href={`${apiRoot}/studies/files/${encodeURIComponent(a.id)}`} onClick={(event) => { event.preventDefault(); void fetch(`${apiRoot}/studies/files/${encodeURIComponent(a.id)}`, { headers: { authorization: `Bearer ${token}` } }).then((response) => response.blob()).then((blob) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = a.fileName; link.click(); setTimeout(() => URL.revokeObjectURL(url), 60_000); }).catch(() => setError('Could not download that file.')); }}><BookOpen size={14}/>{a.fileName} · {(a.sizeBytes / 1024 / 1024).toFixed(2)} MB</a>)}</article>)}{!sections.length && <p className="community-muted">No study folders yet.</p>}{error && <p className="chat-error">{error}</p>}</div>;
}

function GroupPolls({ token, id, isAdmin }: { token: string; id: string; isAdmin: boolean }) {
  const [polls, setPolls] = useState<{ id: string; question: string; status: string; my_vote: string | null; options: { id: string; label: string; votes: number }[] }[]>([]); const [question, setQuestion] = useState(''); const [options, setOptions] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { const data = await request<{ polls: typeof polls }>(`/groups/${encodeURIComponent(id)}/polls`, token); setPolls(data.polls); }, [id, token]); useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  useEffect(() => { let stopped = false; let timer: ReturnType<typeof setTimeout> | undefined; let socket: WebSocket | null = null; const connect = () => { if (stopped) return; const ws = new WebSocket(`${wsRoot}/api/ws/polls?token=${encodeURIComponent(token)}`); socket = ws; ws.onmessage = (event) => { try { if (JSON.parse(String(event.data)).type === 'polls-updated') void load(); } catch { /* invalid event */ } }; ws.onclose = () => { if (!stopped) timer = setTimeout(connect, 3000); }; ws.onerror = () => ws.close(); }; connect(); return () => { stopped = true; if (timer) clearTimeout(timer); socket?.close(); }; }, [load, token]);
  const create = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}/polls`, token, { method: 'POST', body: JSON.stringify({ question, options: options.split('\n').map((x) => x.trim()).filter(Boolean) }) }); setQuestion(''); setOptions(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create poll.'); } };
  const vote = async (pollId: string, optionId: string) => { try { await request(`/groups/${encodeURIComponent(id)}/polls/${encodeURIComponent(pollId)}/vote`, token, { method: 'POST', body: JSON.stringify({ optionId }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not vote.'); } };
  const closePoll = async (pollId: string, status: string) => { try { await request(`/groups/${encodeURIComponent(id)}/polls/${encodeURIComponent(pollId)}`, token, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update poll.'); } };
  return <div className="community-resource"><div className="community-resource-heading"><CircleHelp size={20}/><div><b>Group Polls</b><small>Only group members can see these polls</small></div></div>{isAdmin && <form className="community-resource-compose" onSubmit={(e) => void create(e)}><input value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask your group a question"/><textarea value={options} onChange={(e) => setOptions(e.target.value)} placeholder="One option per line"/><button disabled={!question.trim()}><Plus size={15}/> Create poll</button></form>}{polls.map((poll) => <article className="community-poll" key={poll.id}><b>{poll.question}</b>{poll.options.map((option) => <button key={option.id} disabled={!!poll.my_vote || poll.status !== 'open'} onClick={() => void vote(poll.id, option.id)}>{option.label}<span>{poll.my_vote || poll.status === 'closed' ? option.votes : ''}</span></button>)}{isAdmin && <button className="community-poll-toggle" onClick={() => void closePoll(poll.id, poll.status === 'open' ? 'closed' : 'open')}>{poll.status === 'open' ? 'Close poll' : 'Reopen poll'}</button>}{poll.status === 'closed' && <small>Closed</small>}</article>)}{!polls.length && <p className="community-muted">No polls in this group yet.</p>}{error && <p className="chat-error">{error}</p>}</div>;
}
