import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, BookOpen, Check, CircleHelp, MessageSquareText, Plus, Send, Users, X } from 'lucide-react';

type ChatMessage = { id: string; username: string; mine: boolean; body: string; created_at: string };
type Dm = { conversation_id: string; peer_username: string; last_message: string | null };
type Group = { id: string; group_number: string; name: string; visibility: 'public' | 'private'; role: 'admin' | 'member' };
type RequestItem = { id: string; sender_id: string; sender_username: string; recipient_id: string; recipient_username: string; created_at: string; incoming: number };
type Invitation = { id: string; group_id: string; group_number: string; name: string; inviter_username: string };

const appOrigin = location.hostname === 'student-addit.pages.dev' || location.hostname.endsWith('.student-addit.pages.dev') ? 'https://student-addit.mgp899123.workers.dev' : '';
const apiRoot = `${appOrigin}/api`;
const wsRoot = appOrigin ? appOrigin.replace(/^http/, 'ws') : `${location.protocol}//${location.host}`;

async function request<T>(path: string, token: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${apiRoot}${path}`, { ...init, headers: { 'content-type': 'application/json', authorization: `Bearer ${token}`, ...init.headers } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Could not complete that action.');
  return data as T;
}

export function CommunityChats({ token }: { token: string }) {
  const [dms, setDms] = useState<Dm[]>([]); const [groups, setGroups] = useState<Group[]>([]);
  const [requests, setRequests] = useState<RequestItem[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [selected, setSelected] = useState<{ kind: 'dm' | 'group'; id: string; label: string } | null>(null);
  const [friendId, setFriendId] = useState(''); const [groupName, setGroupName] = useState(''); const [visibility, setVisibility] = useState<'public' | 'private'>('public'); const [groupPassword, setGroupPassword] = useState('');
  const [groupNumber, setGroupNumber] = useState(''); const [joinPassword, setJoinPassword] = useState(''); const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const refresh = useCallback(async () => {
    const [friendData, groupData] = await Promise.all([request<{ conversations: Dm[]; requests: RequestItem[] }>('/friends', token), request<{ groups: Group[]; invitations: Invitation[] }>('/groups', token)]);
    setDms(friendData.conversations); setRequests(friendData.requests); setGroups(groupData.groups); setInvitations(groupData.invitations);
  }, [token]);
  useEffect(() => { void refresh().catch((e) => setError(e.message)); }, [refresh]);
  const submit = async (event: FormEvent, action: () => Promise<void>) => { event.preventDefault(); setError(''); setNotice(''); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not complete that action.'); } };
  const sendRequest = async (event: FormEvent) => submit(event, async () => { await request('/friend-requests', token, { method: 'POST', body: JSON.stringify({ username: friendId }) }); setFriendId(''); setNotice('Request sent.'); await refresh(); });
  const createGroup = async (event: FormEvent) => submit(event, async () => { const data = await request<{ group: Group }>('/groups', token, { method: 'POST', body: JSON.stringify({ name: groupName, visibility, password: groupPassword }) }); setGroupName(''); setGroupPassword(''); setShowCreate(false); setNotice(`Group created. Share group number ${data.group.group_number}.`); await refresh(); setSelected({ kind: 'group', id: data.group.id, label: data.group.name }); });
  const joinGroup = async (event: FormEvent) => submit(event, async () => { const data = await request<{ group: Group }>('/groups/join', token, { method: 'POST', body: JSON.stringify({ groupNumber, password: joinPassword }) }); setGroupNumber(''); setJoinPassword(''); setNotice(`You joined ${data.group.name}.`); await refresh(); setSelected({ kind: 'group', id: data.group.id, label: data.group.name }); });
  const respond = async (type: 'friend-requests' | 'group-invitations', item: { id: string }, action: 'accept' | 'decline') => {
    setError(''); try { await request(`/${type}/${encodeURIComponent(item.id)}/respond`, token, { method: 'POST', body: JSON.stringify({ action }) }); await refresh(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not respond.'); }
  };
  return <div className="page-wrap community-chat-page"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-number">02</span> YOUR PEOPLE, YOUR ROOMS</div><h1>Find your <i>people.</i></h1><p className="subhead">Start a private conversation or make a room for your group.</p></div><button className="small-action" onClick={() => setShowCreate((v) => !v)}><Plus size={16}/> Create a group <ArrowUpRight size={14}/></button></div>
    {(error || notice) && <div className={`study-status ${error ? 'error' : ''}`}>{error || notice}</div>}
    <div className="community-grid"><section className="community-directory">
      <form className="community-inline-form" onSubmit={(e) => void sendRequest(e)}><div><span className="eyebrow">PRIVATE CHAT</span><strong>Find someone by adda ID</strong></div><div className="community-form-row"><input value={friendId} onChange={(e) => setFriendId(e.target.value)} placeholder="Their adda ID" aria-label="Adda ID"/><button disabled={!friendId.trim()}><Users size={16}/> Send request</button></div></form>
      {showCreate && <form className="community-inline-form" onSubmit={(e) => void createGroup(e)}><div><span className="eyebrow">A ROOM OF YOUR OWN</span><strong>Create a group</strong></div><input required minLength={2} maxLength={80} value={groupName} onChange={(e) => setGroupName(e.target.value)} placeholder="Group name"/><div className="community-form-row"><select value={visibility} onChange={(e) => setVisibility(e.target.value as 'public' | 'private')}><option value="public">Public · group number only</option><option value="private">Private · number + password</option></select>{visibility === 'private' && <input required minLength={6} type="password" value={groupPassword} onChange={(e) => setGroupPassword(e.target.value)} placeholder="Group password"/>}<button><Plus size={16}/> Create</button></div></form>}
      <form className="community-join-form" onSubmit={(e) => void joinGroup(e)}><div><span className="eyebrow">JOIN A GROUP</span><strong>Have a group number?</strong></div><div className="community-form-row"><input inputMode="numeric" value={groupNumber} onChange={(e) => setGroupNumber(e.target.value)} placeholder="8-digit number" aria-label="Group number"/>{joinPassword !== null && <input type="password" value={joinPassword} onChange={(e) => setJoinPassword(e.target.value)} placeholder="Password if private" aria-label="Group password"/>}<button disabled={!groupNumber.trim()}><ArrowUpRight size={16}/> Join</button></div></form>
      {!!requests.length && <div className="community-list-block"><h3>Friend requests</h3>{requests.map((item) => <div className="community-person" key={item.id}><span className="community-avatar">{(item.incoming ? item.sender_username : item.recipient_username)[0]?.toUpperCase()}</span><div><b>#{item.incoming ? item.sender_username : item.recipient_username}</b><small>{item.incoming ? 'Wants to chat' : 'Waiting for their reply'}</small></div>{!!item.incoming && <div className="community-actions"><button onClick={() => void respond('friend-requests', item, 'accept')} title="Accept"><Check size={16}/></button><button onClick={() => void respond('friend-requests', item, 'decline')} title="Decline"><X size={16}/></button></div>}</div>)}</div>}
      {!!invitations.length && <div className="community-list-block"><h3>Group invitations</h3>{invitations.map((item) => <div className="community-person" key={item.id}><span className="community-avatar"><Users size={16}/></span><div><b>{item.name}</b><small>From #{item.inviter_username} · {item.group_number}</small></div><div className="community-actions"><button onClick={() => void respond('group-invitations', item, 'accept')}><Check size={16}/></button><button onClick={() => void respond('group-invitations', item, 'decline')}><X size={16}/></button></div></div>)}</div>}
      <div className="community-list-block"><h3>Private chats <span>{dms.length}</span></h3>{dms.map((dm) => <button className={`community-room-link ${selected?.id === dm.conversation_id ? 'selected' : ''}`} key={dm.conversation_id} onClick={() => setSelected({ kind: 'dm', id: dm.conversation_id, label: `#${dm.peer_username}` })}><span className="community-avatar">{dm.peer_username[0]?.toUpperCase()}</span><span><b>#{dm.peer_username}</b><small>{dm.last_message || 'Your conversation is ready.'}</small></span><MessageSquareText size={16}/></button>)}{!dms.length && <p className="community-muted">Accepted requests will appear here.</p>}</div>
      <div className="community-list-block"><h3>Your groups <span>{groups.length}</span></h3>{groups.map((group) => <button className={`community-room-link ${selected?.id === group.id ? 'selected' : ''}`} key={group.id} onClick={() => setSelected({ kind: 'group', id: group.id, label: group.name })}><span className="community-avatar"><Users size={16}/></span><span><b>{group.name}</b><small>#{group.group_number} · {group.visibility}{group.role === 'admin' ? ' · admin' : ''}</small></span><ArrowUpRight size={16}/></button>)}{!groups.length && <p className="community-muted">Create a group or join with its number.</p>}</div>
    </section>
    <section className="community-room">{selected ? <CommunityRoom key={`${selected.kind}:${selected.id}`} token={token} kind={selected.kind} id={selected.id} label={selected.label} isAdmin={groups.some((g) => g.id === selected.id && g.role === 'admin')} onRefresh={refresh}/> : <div className="community-room-empty"><div><MessageSquareText size={25}/></div><h2>Your next good conversation.</h2><p>Choose a private chat or group, or send someone a request by adda ID.</p></div>}</section></div>
  </div>;
}

function CommunityRoom({ token, kind, id, label, isAdmin, onRefresh }: { token: string; kind: 'dm' | 'group'; id: string; label: string; isAdmin: boolean; onRefresh: () => Promise<void> }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [hasOlder, setHasOlder] = useState(false); const [value, setValue] = useState(''); const [error, setError] = useState(''); const [live, setLive] = useState(false); const [section, setSection] = useState<'chat' | 'studies' | 'polls'>('chat'); const socketRef = useRef<WebSocket | null>(null); const listRef = useRef<HTMLDivElement>(null); const preserveScrollRef = useRef<{ height: number; top: number } | null>(null);
  const messagePath = kind === 'dm' ? `/conversations/${encodeURIComponent(id)}/messages` : `/groups/${encodeURIComponent(id)}/messages`;
  const load = useCallback(async () => { const data = await request<{ messages: ChatMessage[] }>(messagePath, token); setMessages(data.messages); setHasOlder(data.messages.length === 200); }, [messagePath, token]);
  const loadOlder = async () => { const first = messages[0]; if (!first) return; try { const data = await request<{ messages: ChatMessage[] }>(`${messagePath}?before=${encodeURIComponent(`${first.created_at}|${first.id}`)}`, token); if (listRef.current) preserveScrollRef.current = { height: listRef.current.scrollHeight, top: listRef.current.scrollTop }; setMessages((current) => [...data.messages, ...current]); setHasOlder(data.messages.length === 200); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load older messages.'); } };
  useEffect(() => { void load().catch((e) => setError(e.message)); let stopped = false; let timer: ReturnType<typeof setTimeout> | undefined; let delay = 1000;
    const connect = () => { if (stopped) return; const ws = new WebSocket(`${wsRoot}/api/ws/room?kind=${kind}&id=${encodeURIComponent(id)}&token=${encodeURIComponent(token)}`); socketRef.current = ws;
      ws.onopen = () => { if (!stopped) { setLive(true); delay = 1000; void load(); } }; ws.onmessage = (event) => { try { const data = JSON.parse(String(event.data)); if (data.type === 'message' && data.message?.id) setMessages((current) => current.some((m) => m.id === data.message.id) ? current : [...current, data.message as ChatMessage]); } catch { /* ignore invalid frames */ } };
      ws.onclose = () => { if (!stopped) { setLive(false); timer = setTimeout(connect, delay); delay = Math.min(delay * 2, 8000); } }; ws.onerror = () => ws.close(); };
    connect(); return () => { stopped = true; if (timer) clearTimeout(timer); socketRef.current?.close(); socketRef.current = null; };
  }, [id, kind, load, token]);
  useEffect(() => { const list = listRef.current; if (!list) return; const preserve = preserveScrollRef.current; if (preserve) { list.scrollTop = preserve.top + list.scrollHeight - preserve.height; preserveScrollRef.current = null; } else list.scrollTop = list.scrollHeight; }, [messages]);
  const send = (event: FormEvent) => { event.preventDefault(); const body = value.trim(); if (!body || socketRef.current?.readyState !== WebSocket.OPEN) return; socketRef.current.send(JSON.stringify({ body })); setValue(''); };
  return <><header className="community-room-head"><div className="community-avatar"><MessageSquareText size={18}/></div><div><b>{label}</b><small>{kind === 'dm' ? 'PRIVATE CHAT · ONLY YOU TWO' : `GROUP ROOM · ${isAdmin ? 'YOU ARE ADMIN' : 'MEMBER'}`}</small></div><span className={`live-status ${live ? '' : 'offline'}`}><i className={live ? 'online-dot' : 'offline-dot'}/>{live ? 'LIVE' : 'RECONNECTING'}</span></header>
    {kind === 'group' && <div className="community-room-tabs"><button className={section === 'chat' ? 'active' : ''} onClick={() => setSection('chat')}><MessageSquareText size={15}/> Chat</button><button className={section === 'studies' ? 'active' : ''} onClick={() => setSection('studies')}><BookOpen size={15}/> Studies</button><button className={section === 'polls' ? 'active' : ''} onClick={() => setSection('polls')}><CircleHelp size={15}/> Polls</button></div>}
    {section === 'chat' ? <>{hasOlder && <button className="community-load-older" onClick={() => void loadOlder()}>Load earlier messages</button>}<div className="community-message-list" ref={listRef}>{messages.length ? messages.map((m) => <article className={`community-message ${m.mine ? 'mine' : ''}`} key={m.id}><div className="community-message-meta"><b>#{m.username}</b><time>{new Date(m.created_at.replace(' ', 'T') + (m.created_at.includes('Z') ? '' : 'Z')).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div><p>{m.body}</p></article>) : <div className="community-room-empty small"><MessageSquareText size={22}/><p>Send the first message.</p></div>}</div><form className="composer" onSubmit={send}><input disabled={!live} value={value} onChange={(e) => setValue(e.target.value)} maxLength={2000} placeholder={live ? 'Say something nice...' : 'Reconnecting to this room…'} aria-label="Message"/><button disabled={!live || !value.trim()}><Send size={18}/></button></form>{error && <div className="chat-error">{error}</div>}</> : kind === 'group' && section === 'studies' ? <GroupStudies token={token} id={id} isAdmin={isAdmin}/> : kind === 'group' ? <GroupPolls token={token} id={id} isAdmin={isAdmin}/> : null}
    {kind === 'group' && <GroupManage token={token} id={id} isAdmin={isAdmin} onRefresh={onRefresh}/>}
  </>;
}

function GroupManage({ token, id, isAdmin, onRefresh }: { token: string; id: string; isAdmin: boolean; onRefresh: () => Promise<void> }) {
  const [username, setUsername] = useState(''); const [members, setMembers] = useState<{ user_id: string; username: string; role: string }[]>([]); const [groupName, setGroupName] = useState(''); const [visibility, setVisibility] = useState<'public' | 'private'>('public'); const [password, setPassword] = useState(''); const [groupNumber, setGroupNumber] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { const data = await request<{ members: typeof members; group: { name: string; visibility: 'public' | 'private'; group_number: string } }>(`/groups/${encodeURIComponent(id)}`, token); setMembers(data.members); setGroupName(data.group.name); setVisibility(data.group.visibility); setGroupNumber(data.group.group_number); }, [id, token]); useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  if (!isAdmin) return null;
  const invite = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}/invitations`, token, { method: 'POST', body: JSON.stringify({ username }) }); setUsername(''); setError('Invitation sent.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not invite member.'); } };
  const save = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}`, token, { method: 'PATCH', body: JSON.stringify({ name: groupName, visibility, password }) }); setPassword(''); setError('Group settings saved.'); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save settings.'); } };
  const remove = async (userId: string) => { try { await request(`/groups/${encodeURIComponent(id)}/members?userId=${encodeURIComponent(userId)}`, token, { method: 'DELETE' }); await load(); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove member.'); } };
  return <details className="community-admin-tools"><summary>Group admin · manage room</summary><p className="community-group-number">GROUP NUMBER <b>{groupNumber}</b> · Share this to help people find the group.</p><form className="community-resource-compose" onSubmit={(e) => void save(e)}><input value={groupName} onChange={(e) => setGroupName(e.target.value)} placeholder="Group name"/><div className="community-form-row"><select value={visibility} onChange={(e) => setVisibility(e.target.value as 'public' | 'private')}><option value="public">Public</option><option value="private">Private</option></select>{visibility === 'private' && <input type="password" minLength={6} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="New group password"/>}<button><Check size={15}/> Save</button></div></form><form className="community-form-row" onSubmit={(e) => void invite(e)}><input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Invite by adda ID"/><button><Plus size={15}/> Invite</button></form>{members.map((m) => <div className="community-member-row" key={m.user_id}><span>#{m.username}</span><small>{m.role}</small>{m.role !== 'admin' && <button onClick={() => void remove(m.user_id)}>Remove</button>}</div>)}{error && <p className="community-muted">{error}</p>}</details>;
}

function GroupStudies({ token, id, isAdmin }: { token: string; id: string; isAdmin: boolean }) {
  const [sections, setSections] = useState<{ id: string; name: string; post_count: number }[]>([]); const [selected, setSelected] = useState(''); const [posts, setPosts] = useState<{ id: string; body: string; author_username: string; created_at: string; attachments?: { id: string; fileName: string; contentType: string; sizeBytes: number }[] }[]>([]); const [name, setName] = useState(''); const [body, setBody] = useState(''); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState('');
  const loadSections = useCallback(async () => { const data = await request<{ sections: typeof sections }>(`/groups/${encodeURIComponent(id)}/studies`, token); setSections(data.sections); if (!selected && data.sections[0]) setSelected(data.sections[0].id); }, [id, selected, token]);
  const loadPosts = useCallback(async () => { if (!selected) return setPosts([]); const data = await request<{ posts: typeof posts }>(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(selected)}`, token); setPosts(data.posts); }, [id, selected, token]);
  useEffect(() => { void loadSections().catch((e) => setError(e.message)); }, [loadSections]); useEffect(() => { void loadPosts().catch((e) => setError(e.message)); }, [loadPosts]);
  useEffect(() => { if (!selected) return; let stopped = false; let timer: ReturnType<typeof setTimeout> | undefined; let socket: WebSocket | null = null; const connect = async () => { try { const { ticket } = await request<{ ticket: string }>('/studies/ws-ticket', token, { method: 'POST', body: JSON.stringify({ sectionId: selected }) }); if (stopped) return; const ws = new WebSocket(`${wsRoot}/api/ws/studies?sectionId=${encodeURIComponent(selected)}&ticket=${encodeURIComponent(ticket)}`); socket = ws; ws.onmessage = (event) => { try { if (JSON.parse(String(event.data)).type !== 'connected') { void loadPosts(); void loadSections(); } } catch { void loadPosts(); } }; ws.onclose = () => { if (!stopped) timer = setTimeout(() => void connect(), 2500); }; ws.onerror = () => ws?.close(); } catch { if (!stopped) timer = setTimeout(() => void connect(), 4500); } }; void connect(); return () => { stopped = true; if (timer) clearTimeout(timer); socket?.close(); }; }, [selected, token, loadPosts, loadSections]);
  const createSection = async (e: FormEvent) => { e.preventDefault(); try { const data = await request<{ section: { id: string } }>(`/groups/${encodeURIComponent(id)}/studies/sections`, token, { method: 'POST', body: JSON.stringify({ name }) }); setName(''); setSelected(data.section.id); await loadSections(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create folder.'); } };
  const post = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(selected)}`, token, { method: 'POST', body: JSON.stringify({ body }) }); setBody(''); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not post.'); } };
  const upload = async (e: FormEvent) => { e.preventDefault(); if (!file || !selected) return; try { const response = await fetch(`${apiRoot}/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(selected)}/files`, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': file.type || 'application/octet-stream', 'x-file-name': encodeURIComponent(file.name) }, body: file }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Could not upload this file.'); setFile(null); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not upload this file.'); } };
  const archive = async (sectionId: string) => { try { await request(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(sectionId)}`, token, { method: 'PATCH', body: JSON.stringify({ archived: true }) }); if (selected === sectionId) setSelected(''); await loadSections(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not archive folder.'); } };
  const renameSection = async (sectionId: string, current: string) => { const next = window.prompt('Rename this Study folder', current); if (next === null || !next.trim()) return; try { await request(`/groups/${encodeURIComponent(id)}/studies/sections/${encodeURIComponent(sectionId)}`, token, { method: 'PATCH', body: JSON.stringify({ name: next }) }); await loadSections(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not rename folder.'); } };
  const editPost = async (postId: string, current: string) => { const next = window.prompt('Edit this study note', current); if (next === null || !next.trim()) return; try { await request(`/groups/${encodeURIComponent(id)}/studies/posts/${encodeURIComponent(postId)}`, token, { method: 'PATCH', body: JSON.stringify({ body: next }) }); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update note.'); } };
  const deletePost = async (postId: string) => { if (!window.confirm('Remove this study post and its attachment?')) return; try { await request(`/groups/${encodeURIComponent(id)}/studies/posts/${encodeURIComponent(postId)}`, token, { method: 'DELETE' }); await loadPosts(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove post.'); } };
  return <div className="community-resource"><div className="community-resource-heading"><BookOpen size={20}/><div><b>Group Studies</b><small>Shared with members of this group</small></div></div>{isAdmin && <form className="community-form-row" onSubmit={(e) => void createSection(e)}><input value={name} onChange={(e) => setName(e.target.value)} placeholder="New study folder"/><button><Plus size={15}/> Folder</button></form>}<div className="community-study-sections">{sections.map((s) => <span className={selected === s.id ? 'active' : ''} key={s.id}><button onClick={() => setSelected(s.id)}>{s.name}</button>{isAdmin && <><button title="Rename folder" onClick={() => void renameSection(s.id, s.name)}>✎</button><button title="Archive folder" onClick={() => void archive(s.id)}><X size={12}/></button></>}</span>)}</div>{selected && isAdmin && <><form className="community-resource-compose" onSubmit={(e) => void post(e)}><textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder="Share a study note..."/><button disabled={!body.trim()}><Send size={15}/> Post</button></form><form className="community-form-row community-file-upload" onSubmit={(e) => void upload(e)}><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.gif,.txt,.doc,.docx,.ppt,.pptx,.xls,.xlsx" onChange={(e) => setFile(e.target.files?.[0] ?? null)}/><button disabled={!file}><BookOpen size={15}/> Upload file</button></form></>}{posts.map((p) => <article className="community-resource-post" key={p.id}><div className="community-study-post-head"><small>#{p.author_username}</small>{isAdmin && <span><button onClick={() => void editPost(p.id, p.body)} title="Edit note">Edit</button><button onClick={() => void deletePost(p.id)} title="Remove post">Remove</button></span>}</div>{p.body && <p>{p.body}</p>}{p.attachments?.map((a) => <a key={a.id} href={`${apiRoot}/studies/files/${encodeURIComponent(a.id)}`} onClick={(event) => { event.preventDefault(); void fetch(`${apiRoot}/studies/files/${encodeURIComponent(a.id)}`, { headers: { authorization: `Bearer ${token}` } }).then((response) => response.blob()).then((blob) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = a.fileName; link.click(); setTimeout(() => URL.revokeObjectURL(url), 60_000); }).catch(() => setError('Could not download that file.')); }}><BookOpen size={14}/>{a.fileName} · {(a.sizeBytes / 1024 / 1024).toFixed(2)} MB</a>)}</article>)}{!sections.length && <p className="community-muted">No study folders yet.</p>}{error && <p className="chat-error">{error}</p>}</div>;
}

function GroupPolls({ token, id, isAdmin }: { token: string; id: string; isAdmin: boolean }) {
  const [polls, setPolls] = useState<{ id: string; question: string; status: string; my_vote: string | null; options: { id: string; label: string; votes: number }[] }[]>([]); const [question, setQuestion] = useState(''); const [options, setOptions] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { const data = await request<{ polls: typeof polls }>(`/groups/${encodeURIComponent(id)}/polls`, token); setPolls(data.polls); }, [id, token]); useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  useEffect(() => { let stopped = false; let timer: ReturnType<typeof setTimeout> | undefined; let socket: WebSocket | null = null; const connect = () => { if (stopped) return; const ws = new WebSocket(`${wsRoot}/api/ws/polls?token=${encodeURIComponent(token)}`); socket = ws; ws.onmessage = (event) => { try { if (JSON.parse(String(event.data)).type === 'polls-updated') void load(); } catch { /* invalid event */ } }; ws.onclose = () => { if (!stopped) timer = setTimeout(connect, 3000); }; ws.onerror = () => ws.close(); }; connect(); return () => { stopped = true; if (timer) clearTimeout(timer); socket?.close(); }; }, [load, token]);
  const create = async (e: FormEvent) => { e.preventDefault(); try { await request(`/groups/${encodeURIComponent(id)}/polls`, token, { method: 'POST', body: JSON.stringify({ question, options: options.split('\n').map((x) => x.trim()).filter(Boolean) }) }); setQuestion(''); setOptions(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create poll.'); } };
  const vote = async (pollId: string, optionId: string) => { try { await request(`/groups/${encodeURIComponent(id)}/polls/${encodeURIComponent(pollId)}/vote`, token, { method: 'POST', body: JSON.stringify({ optionId }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not vote.'); } };
  const closePoll = async (pollId: string, status: string) => { try { await request(`/groups/${encodeURIComponent(id)}/polls/${encodeURIComponent(pollId)}`, token, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update poll.'); } };
  return <div className="community-resource"><div className="community-resource-heading"><CircleHelp size={20}/><div><b>Group Polls</b><small>Only group members can see these polls</small></div></div>{isAdmin && <form className="community-resource-compose" onSubmit={(e) => void create(e)}><input value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask your group a question"/><textarea value={options} onChange={(e) => setOptions(e.target.value)} placeholder="One option per line"/><button disabled={!question.trim()}><Plus size={15}/> Create poll</button></form>}{polls.map((poll) => <article className="community-poll" key={poll.id}><b>{poll.question}</b>{poll.options.map((option) => <button key={option.id} disabled={!!poll.my_vote || poll.status !== 'open'} onClick={() => void vote(poll.id, option.id)}>{option.label}<span>{poll.my_vote || poll.status === 'closed' ? option.votes : ''}</span></button>)}{isAdmin && <button className="community-poll-toggle" onClick={() => void closePoll(poll.id, poll.status === 'open' ? 'closed' : 'open')}>{poll.status === 'open' ? 'Close poll' : 'Reopen poll'}</button>}{poll.status === 'closed' && <small>Closed</small>}</article>)}{!polls.length && <p className="community-muted">No polls in this group yet.</p>}{error && <p className="chat-error">{error}</p>}</div>;
}
